<?php
return array (
  'app' => 'Admin',
  'model' => 'ProPrice',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '商品价格',
  'icon' => 'calculator',
  'remark' => '商品价格',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'ProPrice',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '产品查询',
      'icon' => '',
      'remark' => '价格查询',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'ProPrice',
      'action' => 'add_property',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '添加类型',
      'icon' => '',
      'remark' => '添加商品的属性',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'ProPrice',
      'action' => 'pinlei_list',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '商品品类',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'ProPrice',
      'action' => 'parts_index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '配件列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);