<?php
return array (
  'app' => 'Admin',
  'model' => 'Inform',
  'action' => 'defaul',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => 'App管理',
  'icon' => 'android',
  'remark' => '',
  'listorder' => '1',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Inform',
      'action' => 'de',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '师傅端',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'AppInform',
          'action' => 'info_list',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '消息列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'AppInform',
          'action' => 'taking_read',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '接单必读',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'AppInform',
          'action' => 'user_agreement',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '用户协议',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'AppInform',
          'action' => 'about_platform',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '关于平台',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'AppInform',
          'action' => 'version_number',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '版本号',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Inform',
      'action' => 'a',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '个人端',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'AppOwn',
          'action' => 'user_agreement',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '用户协议',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'AppOwn',
          'action' => 'about_platform',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '关于平台',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'AppOwn',
          'action' => 'version_number',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '版本号',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
  ),
);