<?php
return array (
  'app' => 'Admin',
  'model' => 'Order',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '订单管理',
  'icon' => 'shekel (alias)',
  'remark' => '订单管理',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Order',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '订单查询',
      'icon' => '',
      'remark' => '查询订单',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Order',
      'action' => 'far_const_order_list',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '远程费单',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Order',
      'action' => 'examine',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '订单审核',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Order',
      'action' => 'proportion',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '利率调整',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Order',
      'action' => 'repair_list',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '维修师傅',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Order',
      'action' => 'not_access_order',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '等待接单',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);